# TODO: https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template
name: 'build & deploy: echo'

on:
  push:
    branches: [ main ]
    paths:
      - 'echo/**'
      - '.github/workflows/echo.yml'
  pull_request:
    branches: [ main ]
    paths: ['echo/**']

jobs:
  build:
    runs-on: ubuntu-latest
    #container: amazon/aws-cli:2.2.35

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Artifact
        run: |
          pushd echo &> /dev/null
          make build
          echo "ARTIFACT=./echo/__dist/index.zip" >> $GITHUB_ENV

      - name: Deploy Artifact
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_SECRET }}
          AWS_REGION: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_REGION }}
        run: |
          aws --version
          VERSION_ID=$(aws s3api put-object \
            --body ${{ env.ARTIFACT }} \
            --bucket ${{ secrets.LAMBDA_DEATHSTAR_3_S3_BUCKET }} \
            --key ${{ secrets.LAMBDA_DEATHSTAR_3_S3_KEY }} \
            --query 'VersionId' \
            --output text \
          )
          echo VERSION $VERSION_ID

          #aws s3api list-object-versions \
            #--bucket ${{ secrets.LAMBDA_DEATHSTAR_3_S3_BUCKET }} \
            #--prefix ${{ secrets.LAMBDA_DEATHSTAR_3_S3_KEY }}
          aws lambda update-function-code \
            --function-name deathstar-3 \
            --s3-bucket ${{ secrets.LAMBDA_DEATHSTAR_3_S3_BUCKET }} \
            --s3-key ${{ secrets.LAMBDA_DEATHSTAR_3_S3_KEY }} \
            --s3-object-version ${VERSION_ID} \
            --publish

