# TODO: https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template
name: 'build & deploy: echo'

on:
  push:
    branches: [ main ]
    paths:
      - 'echo/**'
      - '.github/workflows/echo.yml'
  pull_request:
    branches: [ main ]
    paths: ['echo/**']

jobs:
  build:
    runs-on: ubuntu-latest
    #container: amazon/aws-cli:2.2.35

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Artifact
        run: |
          env | sort
          pushd echo &> /dev/null
          make build
          # docker containers have a different GITHUB_WORKSPACE directory than
          # non-docker run commands
          echo "ARTIFACT=./echo/__dist/index.zip" >> $GITHUB_ENV

      - name: Deploy Artifact
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_SECRET }}
          AWS_REGION: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_REGION }}
        run: |
          aws --version
          S3_URL=s3://${{ secrets.LAMBDA_DEATHSTAR_3_S3_BUCKET }}/${{ secrets.LAMBDA_DEATHSTAR_3_S3_KEY }}
          aws s3 ls ${S3_URL}
          aws s3 cp \
            ${{ env.ARTIFACT }} \
            ${S3_URL}
          aws s3api list-object-versions \
            --bucket ${{ secrets.LAMBDA_DEATHSTAR_3_S3_BUCKET }} \
            --prefix ${{ secrets.LAMBDA_DEATHSTAR_3_S3_KEY }}

      #- name: Upload to S3
        #uses: docker://amazon/aws-cli:2.2.35
        #env:
          #AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_SECRET }}
          #AWS_REGION: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_REGION }}
        #with:
          #args: s3 cp ${{ env.ARTIFACT }} ${{ secrets.LAMBDA_DEATHSTAR_3_S3_URL }}
