# TODO: https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization#creating-a-workflow-template
name: echo deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'echo/**'
      - '.github/workflows/echo.yml'
  pull_request:
    branches: [ main ]
    paths: ['echo/**']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Artifact
        uses: actions/checkout@v2
        run: |
          echo "Hello!"
          pwd

      #- name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_ID }}
      #    aws-secret-access-key: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_SECRET }}
      #    # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
      #    aws-region: ap-northeast-1

      #- name: Upload to S3
      #  uses: docker://amazon/aws-cli:2.0.7
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_SECRET }}
      #  with:
      #    args: s3 cp ${{ secrets.LAMBDA_DEATHSTAR_3_AWS_S3_URL }} /github/home/downloaded_file
